name: Android CI (Kotlin)

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Android Lint
      run: ./gradlew lintDebug

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1.9.1
      if: always()
      with:
        name: Android Unit Tests Report
        path: '**/test-results/**/*.xml'
        reporter: java-junit
        fail-on-error: 'true'
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
